name: gradle build and deploy jar file to aws lambda 

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Gradle setup
        run: gradle wrapper
      
      # build fat Jar
      - name: gradlew build
        run: ./gradlew build
